### ISSUE TITLE
Red X issue

### ISSUE THREAD

**Issue by coolsheets** [R-ArcGIS/r-bridge-install#100]
I wish to load the bridge and have run into the same issue as some previous users.  The R Integration.pyt shows with a red x in catalog.  ArcGIS Desktop 10.8.1.14362, with 64 bit background geoprocessing, R x64 4.1.0
![image](https://user-images.githubusercontent.com/64555593/124300539-ece59180-db1b-11eb-9fb6-a7751be30ec7.png)

**Comment by orhuna** [comment]
@coolsheets I believe with the background 64-bit, [this](https://desktop.arcgis.com/en/arcmap/latest/analyze/executing-tools/64bit-background.htm) is what you are referring to.

Did you try using this toolbox with a 32 bit R version? We do run into issues when using 64-bit R inside the ArcGIS Desktop.

**Comment by coolsheets** [comment]
That is correct.
How do I tell ArcGIS to use the 32-bit version of R?  Do I have to uninstall the 64-bit R?

**Comment by coolsheets** [comment]
Here are the Python log:
Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "C:\Program Files (x86)\ArcGIS\r-bridge-install-master\rtools\__init__.py", line 17, in <module>
    from .install_package import install_package
  File "C:\Program Files (x86)\ArcGIS\r-bridge-install-master\rtools\install_package.py", line 45, in <module>
    PACKAGE_VERSION = r_pkg_version()
  File "C:\Program Files (x86)\ArcGIS\r-bridge-install-master\rtools\rpath.py", line 494, in r_pkg_version
    r_package_path = r_pkg_path()
  File "C:\Program Files (x86)\ArcGIS\r-bridge-install-master\rtools\rpath.py", line 473, in r_pkg_path
    for lib_path in r_all_lib_paths():
  File "C:\Program Files (x86)\ArcGIS\r-bridge-install-master\rtools\rpath.py", line 397, in r_all_lib_paths
    r_user_library_path = r_user_lib_path()
  File "C:\Program Files (x86)\ArcGIS\r-bridge-install-master\rtools\rpath.py", line 378, in r_user_lib_path
    if r_version():
  File "C:\Program Files (x86)\ArcGIS\r-bridge-install-master\rtools\rpath.py", line 360, in r_version
    r_version = r_reg_value("Current Version")
  File "C:\Program Files (x86)\ArcGIS\r-bridge-install-master\rtools\rpath.py", line 212, in r_reg_value
    _user_hive(getpass.getuser()), r_path)
  File "C:\Python27\ArcGIS10.8\Lib\getpass.py", line 157, in getuser
    import pwd
ImportError: No module named pwd

**Comment by scdub** [comment]
It looks like the `getuser` call will try the environment variables LOGNAME, USER, LNAME and USERNAME for your username, and none of them look to be set. After that, it falls back to trying to run `import pwd` which isn't present on Windows. We can change the code to fix this, but for expediency, you might want to open a Command Prompt session, and type `setx USERNAME=coolsheets` where `coolsheets` is replaced by the username you log into your machine with.

**Comment by coolsheets** [comment]
That worked Thank you!
Command in Windows is setx USERNAME coolsheets
No =

**Comment by scdub** [comment]
@coolsheets glad it worked! Thanks for the catch, fixed the command.
