### ISSUE TITLE
unable to run 'Install R bindings' script

### ISSUE THREAD

**Issue by ancharb** [R-ArcGIS/r-bridge-install#12]
I'm unable to run the 'install R bindings' script in ArcGIS Pro 1.1 (as administrator) with R 3.2.2

Running Windows 8.1 x64 on VMware Fusion

Any help is very appreciated!
A.

Running script InstallBindings...
Traceback (most recent call last):
  File "<string>", line 164, in execute
  File "C:\Users\Ansley Charbonneau\Documents\r-bridge-install-master\r-bridge-install-master\rtools\install_package.py", line 126, in install_package
    r_integration_dir = os.path.join(arcmap_install_path, "Rintegration")
  File "c:\program files\arcgis\pro\bin\Python\lib\ntpath.py", line 108, in join
    result_drive, result_path = splitdrive(path)
  File "c:\program files\arcgis\pro\bin\Python\lib\ntpath.py", line 159, in splitdrive
    if len(p) > 1:
TypeError: object of type 'NoneType' has no len()
Failed to execute (InstallBindings).

**Comment by scw** [comment]
@ancharb Can you get the latest version of the package and see if it works correctly? There was an issue with handling support on Pro that has been resolved. Thanks for the report, Shaun

**Comment by ancharb** [comment]
Good to hear, although I fixed the issue by installing the arcbindings package in R.

Thanks for your response!
