### ISSUE TITLE
Unable to Install Bindings

### ISSUE THREAD

**Issue by simonkassel** [R-ArcGIS/r-bridge-install#24]
I'm getting the following message when I run the script:

**Executing: InstallBindings false
Start Time: Thu Jun 30 16:52:56 2016
Running script InstallBindings...

Traceback (most recent call last):
  File "<string>", line 164, in execute
  File "C:\Users\SimonKassel\Documents\ArcGIS\r-bridge-install-master\rtools\install_package.py", line 191, in install_package
    download_url = release_info()[0]
  File "C:\Users\SimonKassel\Documents\ArcGIS\r-bridge-install-master\rtools\github_release.py", line 67, in release_info
    json_r = parse_json_url(latest_url)
  File "C:\Users\SimonKassel\Documents\ArcGIS\r-bridge-install-master\rtools\github_release.py", line 43, in parse_json_url
    r = request.urlopen(url)
  File "C:\Python27\ArcGIS10.3\Lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\ArcGIS10.3\Lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\Python27\ArcGIS10.3\Lib\urllib2.py", line 422, in _open
    '_open', req)
  File "C:\Python27\ArcGIS10.3\Lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Python27\ArcGIS10.3\Lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Python27\ArcGIS10.3\Lib\urllib2.py", line 1181, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "C:\Python27\ArcGIS10.3\Lib\httplib.py", line 995, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\ArcGIS10.3\Lib\httplib.py", line 1029, in _send_request
    self.endheaders(body)
  File "C:\Python27\ArcGIS10.3\Lib\httplib.py", line 991, in endheaders
    self._send_output(message_body)
  File "C:\Python27\ArcGIS10.3\Lib\httplib.py", line 844, in _send_output
    self.send(msg)
  File "C:\Python27\ArcGIS10.3\Lib\httplib.py", line 806, in send
    self.connect()
  File "C:\Python27\ArcGIS10.3\Lib\httplib.py", line 1194, in connect
    self.timeout, self.source_address)
  File "C:\Python27\ArcGIS10.3\Lib\socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
LookupError: unknown encoding: idna

Failed to execute (InstallBindings).
Failed at Thu Jun 30 16:52:56 2016 (Elapsed Time: 0.02 seconds)**

**Comment by scw** [comment]
Hello Simon,

Interesting. I've made a commit which hopefully at least helps with the error, but isn't a direct fix. A couple of questions:

1. If you type `from encodings import idna` in a Python prompt, does that run correctly?
2. Is the machine connected to the internet?

I can't directly reproduce this error locally, but the above questions will help me pin it down more carefully.

**Comment by simonkassel** [comment]
Thanks for the response. 

My machine is connected to the internet so I don't think that that is the issue. I tried completing step 1 but it did not run correctly. I got the following error:

Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
  File "C:\Python27\ArcGIS10.3\lib\encodings\idna.py", line 3, in <module>
    import stringprep, re, codecs
  File "C:\Python27\ArcGIS10.3\lib\stringprep.py", line 8, in <module>
    from unicodedata import ucd_3_2_0 as unicodedata
ImportError: No module named unicodedata

Let me know if you have any advice based on this. Thanks again

**Comment by scw** [comment]
Thanks for the update. Based on that Python error, I think there may be a missing file in your Python installation. Here on 10.3.1, I see a `C:\Python27\ArcGIS10.3\DLLs\unicodedata.pyd` which should resolve that import, you could try repairing ArcGIS to see if it resolves this issue.

But for the bridge specifically, there is an easier approach &mdash; the tool is failing when downloading the toolbox. Instead, you can use the [offline installation instructions](https://github.com/R-ArcGIS/r-bridge-install#offline-installation) to install the toolbox. That should resolve this issue without having to figure out the underlying Python one.

**Comment by scw** [comment]
Marking this one closed &ndash; don't think there's any direct action to take within the code for this issue.
