### ISSUE TITLE
I can't download it in both way

### ISSUE THREAD

**Issue by agmna** [R-ArcGIS/r-bridge-install#54]
Hi, Please help me to install it.
I try to download it online but I can't .
also I try to download it offline but I can't download arcgisbinding_1.0.0.128.zip this file, the URL is failed.
https://github.com/R-ArcGIS/r-bridge/releases/tag/v1.0.0.128

I don't know the cause.
My windows is 64
R is 32 + 64
My arcgis is 32 10.5

**Comment by agmna** [comment]
Executing: InstallBindings true 3.4.1
Start Time: Wed Oct 11 10:19:28 2017
Running script InstallBindings...

Traceback (most recent call last):
  File "<string>", line 255, in execute
  File "F:\Programs\ArcToolsBox\R_ArcGIS Bridge\Offline\r-bridge-install-master\rtools\install_package.py", line 240, in install_package
    save_url(download_url, package_path)
  File "F:\Programs\ArcToolsBox\R_ArcGIS Bridge\Offline\r-bridge-install-master\rtools\github_release.py", line 23, in save_url
    r = request.urlopen(url)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 1241, in https_open
    context=self._context)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10054] An existing connection was forcibly closed by the remote host>

Failed to execute (InstallBindings).
Failed at Wed Oct 11 10:19:44 2017 (Elapsed Time: 15.85 seconds)

**Comment by agmna** [comment]
Executing: InstallBindings true 3.4.1
Start Time: Wed Oct 11 10:19:28 2017
Running script InstallBindings...

Traceback (most recent call last):
  File "<string>", line 255, in execute
  File "F:\Programs\ArcToolsBox\R_ArcGIS Bridge\Offline\r-bridge-install-master\rtools\install_package.py", line 240, in install_package
    save_url(download_url, package_path)
  File "F:\Programs\ArcToolsBox\R_ArcGIS Bridge\Offline\r-bridge-install-master\rtools\github_release.py", line 23, in save_url
    r = request.urlopen(url)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 1241, in https_open
    context=self._context)
  File "C:\Python27\ArcGIS10.5\Lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10054] An existing connection was forcibly closed by the remote host>

Failed to execute (InstallBindings).
Failed at Wed Oct 11 10:19:44 2017 (Elapsed Time: 15.85 seconds)

**Comment by scw** [comment]
Hello @agmna, I've uploaded a new version of the toolbox which will retry downloads that fail. Could you try it out and let us know if it works for you?

Thanks, Shaun

**Comment by agmna** [comment]
Also it does not work.
what about offline file (arcgisbinding_1.0.0.128.zip), The URL does not work.
put other URL here or update same URL.
Please
