### ISSUE TITLE
R Integration Toolbox not opening. Red exclamation point "!" instead

### ISSUE THREAD

**Issue by chrowe** [R-ArcGIS/r-bridge-install#55]
ArcGIS Pro 2.0.1
R version 3.4.2 (2017-09-28)

![r-sample-tools-install](https://user-images.githubusercontent.com/240115/31586321-40eca40a-b19d-11e7-92cb-d7252b6f5888.gif)

Parsing error: 
Traceback (most recent call last):
  File "C:\Users\cori\GitHub\r-bridge-install\rtools\rpath.py", line 446, in r_pkg_path
    package_path_key = winreg.QueryValueEx(pro_reg, package_key)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "C:\Users\cori\Downloads\r-bridge-install-master\r-bridge-install-master\rtools\__init__.py", line 17, in <module>
    from .install_package import install_package
  File "C:\Users\cori\Downloads\r-bridge-install-master\r-bridge-install-master\rtools\install_package.py", line 45, in <module>
    PACKAGE_VERSION = r_pkg_version()
  File "C:\Users\cori\GitHub\r-bridge-install\rtools\rpath.py", line 476, in r_pkg_version
    r_package_path = r_pkg_path()
  File "C:\Users\cori\GitHub\r-bridge-install\rtools\rpath.py", line 451, in r_pkg_path
    handle_fnf(error)
  File "C:\Users\cori\GitHub\r-bridge-install\rtools\rpath.py", line 51, in handle_fnf
    log_exception(exception)
  File "C:\Users\cori\GitHub\r-bridge-install\rtools\rpath.py", line 65, in log_exception
    log.debug("Exception generated: {}".format(str(err).decode(enc, 'ignore')))
AttributeError: 'str' object has no attribute 'decode'

**Comment by scw** [comment]
@chrowe sorry to hear about this -- I fixed an issue for ArcMap (Python 2), and inadvertently created this one in its place. I've pushed a commit which should fix the issue if you'd like to try again. Also note that with ArcGIS Pro 2.0 and later, you can easily install the bridge without using this toolbox. If you navigate to the backstage (Project menu), select Options > Geoprocessing, the bridge can be installed from that pane.

Cheers, Shaun

p.s. just got back from a trip to Quechee, beautiful part of the country!

**Comment by scw** [comment]
@chrowe I believe we've fixed this issue, if not feel free to reopen it.
